# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "phrases-0.1.0-m8uXUcJ5AADNbVNrVA3b_IUJpXPL_dt4kXmkRWEacj9n";
    path = fetchgit {
      url = "https://github.com/haruki7049/phrases";
      rev = "524d42fa408e0834efcd2835e0e9a849ea1bd238";
      hash = "sha256-/JtfGRmsIg5+cx5KIuLTLqgrxS6H3/Dj0/aglpwqNEc=";
    };
  }
]
