# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "meters-0.1.0-EsVLmyDGAACE-3GCOOjWTlD5YV2ZVUXIxeweZgj5gl5H";
    path = fetchgit {
      url = "https://github.com/haruki7049/meters";
      rev = "567f70a073fc861418f1dc02d05d08de5957e91d";
      hash = "sha256-xyKazXuRU3do+5JnCgpkyZElEmBT59B5COsyrHDrrQg=";
    };
  }
]
