# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "phrases-0.1.0-m8uXUf6GAADLISanJCs5q-TdA1CaLL6a5aK3ULyDRfrw";
    path = fetchgit {
      url = "https://github.com/haruki7049/phrases";
      rev = "187b8e3dddadfa19a2ea7af7f2032b00005a07b9";
      hash = "sha256-KLfppRG60WdVekhKtNZTLuquM+PyiwCz45Eerpb0E0c=";
    };
  }
]
